replicaCount: 1

namespace: transcendence
image:
  repository: to_be_inputed
  version: to_be_inputed

deployment:
  restartPolicy: Always
  backend:
    env:
      DB_URL: to_be_inputed
    port: 5500
  prisma:
    port: 5555
  frontend:
    port: 3000


service:
  protocol: TCP
  type: ClusterIP
  backend:
    port: 5500
  prisma:
    port: 5555
  frontend:
    port: 3000


ingress:
  enabled: true
  class: nginx
  host: transcendence.fedir.hypercube.rocks
  tls:
  - hosts:
      - transcendence.fedir.hypercube.rocks