apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: {{ .Values.image.repository }}/{{ .Chart.Name }}-backend:{{ .Values.image.version }}
          ports:
            - containerPort: {{ .Values.deployment.backend.port }}
            - containerPort: {{ .Values.deployment.prisma.port }}
        - name: {{ .Chart.Name }}-frontend
          image: {{ .Values.image.repository }}/{{ .Chart.Name }}-frontend:{{ .Values.image.version }}
          ports:
            - containerPort: {{ .Values.deployment.frontend.port }}