apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: {{.Values.service.protocol}}
      name: backend
      port: {{.Values.service.backend.port }}
      targetPort: {{.Values.service.backend.port }}
    - protocol: {{.Values.service.protocol}}
      name: frontend
      port: {{.Values.service.frontend.port }}
      targetPort: {{.Values.service.frontend.port }}
    - protocol: {{.Values.service.protocol}}
      name: prisma
      port: {{.Values.service.prisma.port }}
      targetPort: {{.Values.service.prisma.port }}
  type: {{.Values.service.type}}