apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: {{.Values.service.protocol}}
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  type: {{.Values.service.type}}